version: 2.1
jobs:
  build-and-publish-docker:
    executor: docker/default
    steps:
      - setup_remote_docker:
          version: 20.10.7

      - checkout

      - run:
          name: Build Docker image
          command: |
            docker build -t mwyssy/ewp-be:${CIRCLE_BUILD_NUM} .
            docker tag mwyssy/ewp-be:${CIRCLE_BUILD_NUM} mwyssy/ewp-be:latest

      - run:
          name: Log in to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - run:
          name: Push Docker image
          command: |
            docker push mwyssy/ewp-be:${CIRCLE_BUILD_NUM}
            docker push mwyssy/ewp-be:latest

workflows:
  version: 2
  build-and-publish-docker-image:
    jobs:
      - build-and-publish-docker:
          context: dockerhub
