version: 2.1
jobs:
  build-and-publish:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build and push Docker image
          command: |
            echo $DOCKERHUB_USERNAME
            echo $DOCKERHUB_PASSWORD

            docker build -t mwyssy/ewp-be:${CIRCLE_BUILD_NUM} .
            docker tag mwyssy/ewp-be:${CIRCLE_BUILD_NUM} mwyssy/ewp-be:latest
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push mwyssy/ewp-be:${CIRCLE_BUILD_NUM}
            docker push mwyssy/ewp-be:latest

workflows:
  version: 2
  build-and-publish-docker-image:
    jobs:
      - build-and-publish
