version: 2.1
orbs:
  docker: circleci/docker@2.2.0
workflows:
  build-and-publish-docker-image:
    jobs:
      - docker/publish:
          image: mwyssy/ewp-be
          name: Publish Docker image
          additional-tags:
            - ${CIRCLE_BUILD_NUM}
            - latest
          registry-url: docker.io
          repo: your-username/your-repo-name
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

