version: 2.1
orbs:
  python: circleci/python@2.1.1
  docker: circleci/docker@2.2.0

jobs:
  build-image-and-push:
    working_directory: ~/elle_wyss_photo_be
    steps:
      - docker/publish:
          image: mwyssy/ewp-be
          tag: ${CIRCLE_BUILD_NUM}
          registry: mwyssy/ewp-be
      
workflows:
  jobs:
    - build-image-and-push