version: 2.1
orbs:
  docker: circleci/docker@2.2.0
workflows:
  build-and-publish-docker-image:
    jobs:
      - docker/build:
          image: mwyssy/ewp-be
          tag: ${CIRCLE_BUILD_NUM}
      - docker/publish:
          image: mwyssy/ewp-be
          name: Publish Docker image
          requires:
            - docker/build
          auth:
            username: $DOCKERHUB_USERNAME
            password: $DOCKERHUB_PASSWORD
          additional-tags:
            - latest
