version: 2.1
orbs:
  docker: circleci/docker@2.2.0

jobs:
  build-and-publish-docker-image:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: mwyssy/ewp-be
          tag: latest,1.${CIRCLE_BUILD_NUM}
      - run:
          command: |
            mkdir .oci 
            echo -e "[DEFAULT]\nuser=${OCI_USER}\nfingerprint=${OCI_FINGERPRINT}\ntenancy=${OCI_TENANCY}\nregion=${OCI_REGION}" > .oci/config
            pwd
            ls
      - docker/push:
          image: mwyssy/ewp-be
          tag: latest,1.${CIRCLE_BUILD_NUM}

workflows:
  commit:
    jobs:
      - build-and-publish-docker-image

          
          
