version: 2.1
orbs:
  docker: circleci/docker@2.2.0

jobs:
  build-and-publish-docker-image:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: mwyssy/ewp-be
          tag: latest,1.${CIRCLE_BUILD_NUM}
      - run:
          command: |
            echo "OCI_USER=$OCI_USER" >> $BASH_ENV
            echo "OCI_KEY=/home/circleci/project/.oci/mike@wyss.co.uk_2023-08-23T20\ 03\ 55.964Z.pem" >> $BASH_ENV
            echo "OCI_FINGERPRINT=$OCI_FINGERPRINT" >> $BASH_ENV
            echo "OCI_TENANCY=$OCI_TENANCY" >> $BASH_ENV
            echo "OCI_REGION=$OCI_REGION" >> $BASH_ENV
            pwd
            ls .oci
      - docker/push:
          image: mwyssy/ewp-be
          tag: latest,1.${CIRCLE_BUILD_NUM}

workflows:
  commit:
    jobs:
      - build-and-publish-docker-image

          
          
